### PR TITLE
Linking to different user profiles (profile discovery)

### PR DESCRIPTION
**Pull request by wcygan**
## What
Adds links to different user profiles

## How 
Using emails as links to a user's profile

## Feed
image

## Profile 1
image

## Profile 2
image

### CODE REVIEW

**Comment by wcygan** [comment]
## What
Added column to center the entire application

## How
A little bit of SCSS

image

image

image

**Comment by wcygan** [comment]
NavBar styling:

image

**Comment by wcygan** [comment]
Using `<TweetColumn tweets={this.tweets} />` in /profile and /home

image

image

**Comment by wcygan** [comment]
Added some scss for tweets

image

**Comment by Faro0q** [comment]
image

**Comment by wcygan** [comment]
i see a warning, not an error :)

**Pull request merged**
